#!/usr/bin/env bash

set -e

export PACKAGE="github.com/WillAbides/gometalintergetter"
export ROOTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export GOPATH="$ROOTPATH/.gopath"
export BASE="$GOPATH/src/$PACKAGE"
export BIN="$BASE/bin"

cd "$ROOTPATH"

VERSION=`git rev-parse HEAD 2>/dev/null`
if [ $? -ne 0 ]; then
  VERSION="$GOMETALINTERGETTER_BUILD_VERSION"
fi
if [ -z "$VERSION" ]; then
  VERSION="unknown"
fi
export VERSION
