#!/bin/bash

set -e
ROOTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$ROOTPATH"
script/build

GOBIN="$GOPATH/bin"
mkdir -p "$GOBIN"
bin/gometalintergetter -i "$GOBIN"

test $# -gt 0 || set -- ./...
echo Linting "$@"
exec "$GOBIN/gometalinter" $@
