#!/bin/bash

set -e
ROOTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
. "$ROOTPATH/script/build-common"
cd "$ROOTPATH"
script/build

GOBIN="$GOPATH/bin"
mkdir -p "$GOBIN"
PATH="$GOBIN:$PATH"
bin/gometalintergetter -i "$GOBIN"

test $# -gt 0 || set -- ./...
echo Linting "$@"
exec gometalinter --vendor $@
